---
- name: Deploy Vivaldi Frontend Application
  hosts: localhost
  become: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages (Git, Nginx, Node.js, and npm)
      apt:
        name:
          - git
          - nginx
          - nodejs
          - npm
        state: present

    - name: Mark /var/www/vivaldi-frontend as a safe Git directory
      command: git config --global --add safe.directory /var/www/vivaldi-frontend

    - name: Clone the Vivaldi frontend repository
      git:
        repo: "https://github.com/ngetichnicholas/Vivaldi20-Frontend.git"
        dest: "/home/ubuntu/vivaldi-frontend"
        version: "main"
        force: yes

    - name: Install npm dependencies
      command: npm install
      args:
        chdir: /home/ubuntu/vivaldi-frontend

    - name: Build the Vue.js project
      command: npm run build
      args:
        chdir: /home/ubuntu/vivaldi-frontend

    - name: Copy built files to Nginx directory
      copy:
        src: /home/ubuntu/vivaldi-frontend/dist/
        dest: /usr/share/nginx/html/dist/
        owner: www-data
        group: www-data
        mode: '0755'
        remote_src: yes

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create Nginx configuration for Vivaldi frontend
      copy:
        dest: /etc/nginx/sites-available/vivaldi-frontend
        content: |
          server {
              listen 80;
              server_name _;

              root /usr/share/nginx/html/dist;
              index index.html;

              location / {
                  try_files $uri $uri/ =404;
              }
          }

    - name: Enable Vivaldi frontend site
      file:
        src: /etc/nginx/sites-available/vivaldi-frontend
        dest: /etc/nginx/sites-enabled/vivaldi-frontend
        state: link
        force: yes

    - name: Adjust permissions for the frontend directory
      file:
        path: /usr/share/nginx/html/dist
        owner: www-data
        group: www-data
        recurse: yes

    - name: Restart Nginx to apply changes
      systemd:
        name: nginx
        state: restarted
        enabled: true
